[package]
name = "warmy"
version = "0.0.1"
authors = [ "pilu",]
edition = "2018"
publish = false

[lib]
path = "src/warmy.rs"

[dependencies.elrond-wasm]
version = "0.25.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.25.0"
